<?xml version="1.0" encoding="UTF-8"?>
<!--
Purpose: This XML document serves as a structured representation of information related to insurance companies. It defines the structure for individual insurance companies, including details such as company name, company location (composed of area, city, and country), number of employees, and company domain. The document specifies that there should be at least one insuranceCompany element within the insuranceCompanies element.  
-->

<!DOCTYPE insuranceCompanies [
  <!--
    Purpose of the insuranceCompany element: Represents an individual insurance company and its associated details.
    Cardinality: "+" is used for companyLocation as the company could have one or more locations in use.
  -->
  <!ELEMENT insuranceCompany (companyName, companyLocation+, numEmployees, companyDomain)>

  <!--
    Purpose of the insuranceCompanies element: Contains a list of insuranceCompany elements (of which at least one is required - "+").
  -->
  <!ELEMENT insuranceCompanies (insuranceCompany+)>

  <!--
    Purpose of the companyName, companyLocation, numEmployees, and companyDomain elements: Represent specific details of an insurance company.
  -->
  <!ELEMENT companyName (#PCDATA)>
  <!ELEMENT companyLocation (area, city, country)>
  <!ELEMENT numEmployees (#PCDATA)>
  <!ELEMENT companyDomain (#PCDATA)>

  <!--
    Purpose of the area, city, and country elements: Represent components of a company location.
  -->
  <!ELEMENT area (#PCDATA)>
  <!ELEMENT city (#PCDATA)>
  <!ELEMENT country (#PCDATA)>
]>

<!-- 
  The insuranceCompanies element contains information about multiple insurance companies.
-->
<insuranceCompanies>
  <!--
    Individual insuranceCompany elements with each representing different companies.
  -->
  <insuranceCompany>
    <!--
      Company name, location details, number of employees, and domain information for the company.
    -->
    <companyName>Allianz</companyName>
    <companyLocation>
      <area>Dublin 4</area>
      <city>Dublin</city>
      <country>Ireland</country>
    </companyLocation>
    <numEmployees>159,000</numEmployees>
    <companyDomain>www.allianz.com</companyDomain>
  </insuranceCompany>
  
  <insuranceCompany>
    <companyName>XYZ Insurance</companyName>
    <companyLocation>
      <area>City Center</area>
      <city>New York</city>
      <country>USA</country>
    </companyLocation>
    <numEmployees>75,000</numEmployees>
    <companyDomain>www.xyzinsurance.com</companyDomain>
  </insuranceCompany>

  <insuranceCompany>
    <companyName>ABC Assurance</companyName>
    <companyLocation>
      <area>Financial District</area>
      <city>San Francisco</city>
      <country>USA</country>
    </companyLocation>
    <numEmployees>50,000</numEmployees>
    <companyDomain>www.abcassurance.com</companyDomain>
  </insuranceCompany>

  <insuranceCompany>
    <companyName>Secure Insure</companyName>
    <companyLocation>
      <area>Canary Wharf</area>
      <city>London</city>
      <country>UK</country>
    </companyLocation>
    <numEmployees>90,000</numEmployees>
    <companyDomain>www.secureinsure.co.uk</companyDomain>
  </insuranceCompany>

  <insuranceCompany>
    <companyName>Global Underwriters</companyName>
    <companyLocation>
      <area>Champs-Élysées</area>
      <city>Paris</city>
      <country>France</country>
    </companyLocation>
    <numEmployees>65,000</numEmployees>
    <companyDomain>www.globalunderwriters.fr</companyDomain>
  </insuranceCompany>

  <insuranceCompany>
    <companyName>Europa Insurance</companyName>
    <companyLocation>
      <area>Paseo de la Castellana</area>
      <city>Madrid</city>
      <country>Spain</country>
    </companyLocation>
    <numEmployees>80,000</numEmployees>
    <companyDomain>www.europainsurance.es</companyDomain>
  </insuranceCompany>
</insuranceCompanies>